import Foundation
import KatanaCore
import KatanaFx

/// Data received/sent from the Katana GO device.
public enum KatanaGoDataBank: Sendable {
  case modeBank(ModeBank)
  case preset(Preset)
  case presetName(String)
  case signalChainBank(SignalChainBank)
  case effectStatusBank(EffectStatusBank)
  case ampBank(AmpBank)
  case bassAmpBank(BassAmpBank)
  case boostBank(BoostBank)
  case bassBank(BassCompLimBank)
  case modSelectionBank(ModSelectionBank)
  case modSingleEffect(KatanaGoFxReadData)
  case fxSelectionBank(FxSelectionBank)
  case fxSingleEffect(KatanaGoFxReadData)
  case delay1Bank(DelayBank)
  case delay2Bank(DelayBank)
  case reverbBank(ReverbBank)
  case soloSwitchLevelBank(SoloSwitchLevelBank)
  case soloBank(SoloBank)
  case contourBank(ContourBank)
  case signalChainPedalFxBank(SignalChainPedalFxBank)
  case pedalFxBank(PedalFxBanks)
  case pedalFxSingleEffect(PedalFxReadData)
  case eq1SelectionBank(EQSelectionBank)
  case eq1ParametricBank(ParametricEQBank)
  case eq1GraphicBank(GraphicEQBank)
  case eq2SelectionBank(EQSelectionBank)
  case eq2ParametricBank(ParametricEQBank)
  case eq2GraphicBank(GraphicEQBank)
  case noiseGateBank(NoiseGateBank)
}

public enum KatanaGoFxReadData: Sendable, Hashable {
  case chorus(ChorusBank)
  case flanger(FlangerBank)
  case phaser(PhaserBank)
  case univibe(UniVibeBank)
  case tremolo(TremoloBank)
  case vibrato(VibratoBank)
  case rotary(RotaryBank)
  case ringMod(RingModBank)
  case slowGear(SlowGearBank)
  case slicer(SlicerBank)
  case comp(CompBank)
  case tWah(TWahBank)
  case autoWah(AutoWahBank)
  case modFxGraphicEQ(ModFxGraphicEQBank)
  case modFxParametricEQ(ModFxParametricEQBank)
  case guitarSim(GuitarSimBank)
  case acSim(ACSimBank)
  case acousticPro(AcousticProBank)
  case waveSynth(WaveSynthBank)
  case octaver(OctaverBank)
  case heavyOctave(HeavyOctaveBank)
  case pitchShifter(PitchShifterBank)
  case harmonist(HarmonistBank)
  case phase90(Phaser90EBank)
  case flanger117E(Flanger117EBank)
  case dc30(DC30Bank)
}

public enum PedalFxReadData: Sendable, Hashable {
  case wah(PedalFxWahBank)
  case bend(PedalFxBendBank)
  case wah95(PedalFxWah95Bank)
}
